### ISSUE TITLE
Where to get GuildID

### ISSUE THREAD

**Issue by hikaoffical1** [face-hh/discordmium#2]
Hi where to get GuildID

**Comment by Aunchers** [comment]
I believe GuildID is just your channels id
To get it 
1.open the server that you will place your bot in
2.Right click a channel (example: #General)
3. Click copy ID

I believe this means that the bot will only send messages in that channel

**Comment by face-hh** [comment]
The guild ID is the server where the bot should register the `/browse` command. You need developer mode enabled to be able to copy the ID.

**Comment by Audomations** [comment]
In order to get your GuildID you must have developer mode which can be located in your settings. (Settings > Advanced > Developer Mode)

![image](https://user-images.githubusercontent.com/96745093/210130807-5a7e0982-284e-4f0b-88ed-7ecb0a5ebeba.png)

Once you turned it on, go to a server and right click the name of it and you should see "Copy ID" click on it and that is your guild id.

![image](https://user-images.githubusercontent.com/96745093/210130844-99b8a1a7-2892-4ca1-98ba-b4c9274257e1.png)
